### PR TITLE
[Mellanox] Add patch to disable hw-management thermal control shell script

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

There is already a user space thermal control feature. In order to avoid conflict, need to disable thermal control shell script on Mellanox hw-management side.

**- How I did it**

Add a patch for hw-mgmt to disable thermal control shell script at build time.

**- How to verify it**

Apply the patch and see the service has been disabled.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by Junchao-Mellanox** [comment]
> As there has already been one patch prefixed with 0001- [0001-Make-hw-mgmt-SimX-compatiable.patch](https://github.com/Azure/sonic-buildimage/blob/master/platform/mellanox/hw-management/0001-Make-hw-mgmt-SimX-compatiable.patch), should this be 0002-?

Now the SimX patch cannot be applied to hw-mgmt, and once Simx patch fail, the rest patch will not be applied too, I have to prefix my patch with 0001 to make sure it can be applied. Should we change the Makefile to make sure that one patch fail would not affect other patch?

**Comment by stephenxs** [comment]
Understood.
Even though having two patches with the same sequence number is not good and neither is that a stable way to make your patch can be installed.
I think you can ask Mykola to fix it or remove the problematic patch and then add yours.
To improve the makefile by skipping problematic patches is better but I think it's better to do that in another PR.

**Comment by Junchao-Mellanox** [comment]
> Understood.
> Even though having two patches with the same sequence number is not good and neither is that a stable way to make your patch can be installed.
> I think you can ask Mykola to fix it or remove the problematic patch and then add yours.
> To improve the makefile by skipping problematic patches is better but I think it's better to do that in another PR.

Already sent an email to Mykola. You are right, two patches with the same sequence number is not good. I'll work with Mykola to fix this.

**Comment by liat-grozovik** [comment]
should this be taken even if thermal control is not part of 201911?

**Comment by Junchao-Mellanox** [comment]
if thermal control is not part of 201911, this patch should not be applied.

**Comment by Junchao-Mellanox** [comment]
Community PR https://github.com/Azure/sonic-buildimage/pull/4550

**Pull request closed without merging**
