### PR TITLE
[port auto-neg] Add yang model for port auto-neg feature

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
**- Why I did it**

Add yang model for port auto-neg feature

**- How I did it**

Add fields adv_speeds, interface_type, adv_interface_types, autoneg

**- How to verify it**

Run build

**- Which release branch to backport (provide reason below if selected)**

- [ ] 201811
- [ ] 201911
- [ ] 202006
- [ ] 202012

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by vadymhlushko-mlnx** [comment]
LGTM, but you need to add the tests, you can use this [PR](https://github.com/Azure/sonic-buildimage/pull/6464) as an example.
When the tests will be ready, please ask @praveen-li to review them.

**Comment by Junchao-Mellanox** [comment]
Sure, will update later.

**Comment by Junchao-Mellanox** [comment]
@vadymhlushko-mlnx could you review again?

**Comment by vadymhlushko-mlnx** [comment]
If You add a new leaf in YANG Models:
Then please add the corresponding config in the same format as in configDB.json to the next file:
[sonic-buildimage/src/sonic-yang-models/tests/yang_model_tests/yangTest.json](https://github.com/Azure/sonic-buildimage/blob/c54a03fade6c822ea25051882a5745ac5b4fcbf2/src/sonic-yang-models/tests/yang_model_tests/yangTest.json#L1297) under the key `"SAMPLE_CONFIG_DB_JSON"`

Then  please build both:
`sonic_yang_mgmt-1.0-py3-none-any.whl`
`sonic_yang_models-1.0-py3-none-any.whl`

Build tests will make sure, that translation works for new leaves in YANG models.

**Comment by Junchao-Mellanox** [comment]
Added new field to `SAMPLE_CONFIG_DB_JSON` and verified with:

```
sonic_yang_mgmt-1.0-py3-none-any.whl
sonic_yang_models-1.0-py3-none-any.whl
```

**Comment by Junchao-Mellanox** [comment]
@vadymhlushko-mlnx could you review again?

**Comment by vadymhlushko-mlnx** [comment]
> @vadymhlushko-mlnx could you review again?

LGTM

**Comment by Junchao-Mellanox** [comment]
Could you approve it so that I can run a CI?

**Comment by vadymhlushko-mlnx** [comment]
> Could you approve it so that I can run a CI?

Please add me to the "Reviewers" section

**Comment by Junchao-Mellanox** [comment]
i suppose u can directly review it by clicking "Files Changed"->"Review changes"

**Review by vadymhlushko-mlnx — APPROVED** [review]
LGTM

**Comment by praveen-li** [comment]
It should be marked as Yang project PR, and should be discussed once in the yang workgroup. thx.

**Comment by Junchao-Mellanox** [comment]
https://github.com/Azure/sonic-buildimage/pull/6948

**Pull request closed without merging**
